# Copyright (c) OpenMMLab. All rights reserved.
"""
PoseC3D demo using pre-computed SAM3-guided pose data.

This script loads pose data from HDF5 cache files generated by batch_sam_pose.py
instead of running pose estimation on the fly. This is useful for:
  - Faster inference when poses are already computed
  - Consistent results across multiple runs
  - Using poses generated with different pose models

Usage:
    # Using row index (recommended - auto-discovers video and cache):
    python demo_skeleton_sam_pose.py --row-idx 45 --config <config> --checkpoint <checkpoint>
    python demo_skeleton_sam_pose.py --row-idx 45 --out-filename custom_output.mp4

    # Using explicit video path:
    python demo_skeleton_sam_pose.py --video video.mp4 --out-filename output.mp4
    python demo_skeleton_sam_pose.py --video video.mp4 --pose-cache /path/to/cache.h5
"""

import argparse
import cv2
import json
import mmcv
import numpy as np
import os
import os.path as osp
import shutil
import subprocess
import torch
import warnings
import h5py
from pathlib import Path
from scipy.optimize import linear_sum_assignment
import sys
from typing import Dict, Optional

from pyskl.apis import inference_recognizer, init_recognizer

try:
    from mmpose.apis import init_pose_model, vis_pose_result
except (ImportError, ModuleNotFoundError, ValueError):
    def init_pose_model(*args, **kwargs):
        pass

    def vis_pose_result(*args, **kwargs):
        pass

    warnings.warn(
        'Failed to import `init_pose_model`, `vis_pose_result` from '
        '`mmpose.apis`. Visualization may be limited. '
    )

FONTFACE = cv2.FONT_HERSHEY_DUPLEX
FONTSCALE = 0.75
FONTCOLOR = (255, 255, 255)  # BGR, white
THICKNESS = 1
LINETYPE = 1

# COCO keypoint indices (first 17 of COCO-WholeBody)
# This allows using poses from whole-body models with COCO-trained action recognition
COCO_KEYPOINT_INDICES = list(range(17))

# Default cache configuration (matches batch_sam_pose.py)
DEFAULT_CACHE_BASE = "/orcd/scratch/bcs/001/sensein/sails/cache_for_tracking"
DEFAULT_DETECTION_CONFIG = "dino-5scale_swin-l_8xb2-36e_coco"
DEFAULT_DET_CONF_THRESH = 0.5
DEFAULT_POSE_CONFIG = "td-hm_hrnet-w48_dark-8xb32-210e_coco-wholebody-384x288"

# Default video metadata path
DEFAULT_VIDEO_META_JSON = "/orcd/data/satra/001/users/brukew/actreg/dataprep/video_meta.json"

# Default output directory for row-based processing
DEFAULT_OUTPUT_DIR = "/orcd/scratch/bcs/001/sensein/sails/feature_processing/pipeline_outputs/skeleton_recognition"


def load_video_metadata(meta_path: str) -> Dict[int, Dict]:
    """
    Load video metadata from JSON file.
    
    Args:
        meta_path: Path to video_meta.json
        
    Returns:
        Dictionary mapping row_idx to video metadata record
    """
    with open(meta_path, 'r') as f:
        data = json.load(f)
    
    # Build lookup by row_idx
    lookup = {rec['row_idx']: rec for rec in data['records']}
    return lookup


def get_video_info_from_row(row_idx: int, meta_lookup: Dict[int, Dict]) -> Optional[Dict]:
    """
    Get video information for a given row index.
    
    Args:
        row_idx: Row index (1-based)
        meta_lookup: Video metadata lookup dictionary
        
    Returns:
        Video metadata record or None if not found
    """
    if row_idx not in meta_lookup:
        return None
    return meta_lookup[row_idx]


def parse_args():
    parser = argparse.ArgumentParser(
        description='PoseC3D demo with cached SAM3 poses',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Using row index (recommended):
  python demo_skeleton_sam_pose.py --row-idx 45
  python demo_skeleton_sam_pose.py --row-idx 45 --out-filename custom_output.mp4

  # Using explicit video path:
  python demo_skeleton_sam_pose.py --video video.mp4 --out-filename output.mp4

  # With custom config/checkpoint:
  python demo_skeleton_sam_pose.py --row-idx 45 --config my_config.py --checkpoint my_ckpt.pth
        """
    )
    
    # Input source: either row-idx or video path
    input_group = parser.add_mutually_exclusive_group()
    input_group.add_argument(
        '--row-idx',
        type=int,
        default=None,
        help='Row index from video_meta.json (1-based). Auto-discovers video and cache paths.')
    input_group.add_argument(
        '--video',
        type=str,
        default=None,
        help='video file/url (alternative to --row-idx)')
    
    parser.add_argument(
        '--out-filename',
        type=str,
        default=None,
        help='output filename (auto-generated if using --row-idx)')
    parser.add_argument(
        '--output-dir',
        type=str,
        default=DEFAULT_OUTPUT_DIR,
        help='output directory for row-based processing')
    parser.add_argument(
        '--video-meta',
        type=str,
        default=DEFAULT_VIDEO_META_JSON,
        help='path to video_meta.json')
    parser.add_argument(
        '--config',
        default='/orcd/data/satra/001/users/brukew/actreg/pyskl/configs/posec3d/slowonly_r50_ntu120_xsub/joint.py',
        help='skeleton action recognition config file path')
    parser.add_argument(
        '--checkpoint',
        default='https://download.openmmlab.com/mmaction/pyskl/ckpt/posec3d/slowonly_r50_ntu120_xsub/joint.pth',
        help='skeleton action recognition checkpoint file/url')
    parser.add_argument(
        '--pose-config',
        default='demo/hrnet_w32_coco_256x192.py',
        help='human pose estimation config file path (for visualization)')
    parser.add_argument(
        '--pose-checkpoint',
        default='https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth',
        help='human pose estimation checkpoint file/url (for visualization)')
    parser.add_argument(
        '--pose-cache',
        type=str,
        default=None,
        help='Path to HDF5 pose cache file. If not provided, auto-discovers from video name.')
    parser.add_argument(
        '--cache-base-path',
        type=str,
        default=DEFAULT_CACHE_BASE,
        help='Base path for pose cache storage')
    parser.add_argument(
        '--det-config-name',
        type=str,
        default=DEFAULT_DETECTION_CONFIG,
        help='Detection config name used in cache filename')
    parser.add_argument(
        '--det-conf-thresh',
        type=float,
        default=DEFAULT_DET_CONF_THRESH,
        help='Detection confidence threshold used in cache filename')
    parser.add_argument(
        '--pose-config-name',
        type=str,
        default=DEFAULT_POSE_CONFIG,
        help='Pose config name used in cache filename')
    parser.add_argument(
        '--label-map',
        default='/orcd/data/satra/001/users/brukew/actreg/pyskl/tools/data/label_map/nturgbd_120.txt',
        help='label map file')
    parser.add_argument(
        '--device', type=str, default='cuda:0', help='CPU/CUDA device option')
    parser.add_argument(
        '--short-side',
        type=int,
        default=480,
        help='specify the short-side length of the image')
    parser.add_argument(
        '--num-keypoints',
        type=int,
        default=17,
        help='Number of keypoints to use (17 for COCO, 133 for COCO-WholeBody)')
    parser.add_argument(
        '--pose-conf-thresh',
        type=float,
        default=0.3,
        help='Keypoint confidence threshold for visualization')
    
    args = parser.parse_args()
    
    # Validate: must have either --row-idx or --video
    if args.row_idx is None and args.video is None:
        parser.error("Must specify either --row-idx or --video")
    
    return args


def get_sam3_pose_cache_path(video_path: str, args) -> Path:
    """
    Generate cache path matching the format from batch_sam_pose.py.
    
    Cache structure:
        {cache_base_path}/pose_sam3/{video_basename}/{det_name}_{thresh}_{pose_name}_sam3guided.h5
    
    Args:
        video_path: Path to the video file
        args: Parsed arguments with cache configuration
        
    Returns:
        Path to the expected HDF5 cache file
    """
    video_basename = Path(video_path).stem
    cache_dir = Path(args.cache_base_path) / "pose_sam3" / video_basename
    
    det_name = args.det_config_name
    pose_name = args.pose_config_name
    filename = f"{det_name}_{args.det_conf_thresh}_{pose_name}_sam3guided.h5"
    
    return cache_dir / filename


def load_pose_cache(cache_path: Path) -> dict:
    """
    Load pose results from HDF5 cache file.
    
    Args:
        cache_path: Path to the HDF5 cache file
        
    Returns:
        Dictionary mapping frame_idx to list of pose dicts:
        {
            frame_idx: [
                {'keypoints': ndarray (num_kpts, 3), 'bbox': ndarray (4,)},
                ...
            ],
            ...
        }
    """
    if not cache_path.exists():
        raise FileNotFoundError(f"Pose cache not found: {cache_path}")
    
    poses = {}
    try:
        with h5py.File(cache_path, 'r') as f:
            # Print cache metadata
            print(f"[DEBUG] Loading pose cache: {cache_path}")
            if 'detection_config' in f.attrs:
                print(f"[DEBUG] Detection config: {f.attrs['detection_config']}")
            if 'pose_config' in f.attrs:
                print(f"[DEBUG] Pose config: {f.attrs['pose_config']}")
            if 'sam3_guided' in f.attrs:
                print(f"[DEBUG] SAM3 guided: {f.attrs['sam3_guided']}")
            
            for frame_key in f.keys():
                frame_idx = int(frame_key.split('_')[1])
                frame_group = f[frame_key]
                
                frame_poses = []
                for pose_key in sorted(frame_group.keys()):
                    pose_group = frame_group[pose_key]
                    frame_poses.append({
                        'keypoints': pose_group['keypoints'][:],
                        'bbox': pose_group['bbox'][:]
                    })
                poses[frame_idx] = frame_poses
                
        print(f"[DEBUG] Loaded poses for {len(poses)} frames")
        return poses
        
    except Exception as e:
        raise RuntimeError(f"Error loading pose cache: {e}")


def frame_extraction(video_path, short_side):
    """
    Extract frames given video_path.

    Args:
        video_path (str): The video_path.
        short_side (int): Target short side length for resizing.
        
    Returns:
        tuple: (frame_paths, frames) - paths to saved frames and frame arrays
    """
    # Load the video, extract frames into ./tmp/video_name
    target_dir = osp.join('./tmp', osp.basename(osp.splitext(video_path)[0]))
    os.makedirs(target_dir, exist_ok=True)
    # Should be able to handle videos up to several hours
    frame_tmpl = osp.join(target_dir, 'img_{:06d}.jpg')
    vid = cv2.VideoCapture(video_path)
    frames = []
    frame_paths = []
    flag, frame = vid.read()
    cnt = 0
    new_h, new_w = None, None
    while flag:
        if new_h is None:
            h, w, _ = frame.shape
            new_w, new_h = mmcv.rescale_size((w, h), (short_side, np.Inf))

        frame = mmcv.imresize(frame, (new_w, new_h))

        frames.append(frame)
        frame_path = frame_tmpl.format(cnt + 1)
        frame_paths.append(frame_path)

        cv2.imwrite(frame_path, frame)
        cnt += 1
        flag, frame = vid.read()

    return frame_paths, frames


def convert_cached_poses_to_format(cached_poses: dict, num_frames: int, 
                                    num_keypoints: int = 17) -> list:
    """
    Convert cached pose dictionary to the list format expected by pose_tracking.
    
    The cached poses are stored frame-by-frame, and we need to convert them
    to a list where each element is a list of keypoint arrays for that frame.
    
    Args:
        cached_poses: Dictionary from load_pose_cache()
        num_frames: Total number of frames in the video
        num_keypoints: Number of keypoints to extract (default 17 for COCO)
        
    Returns:
        List of lists, where pose_results[frame_idx] is a list of keypoint arrays
    """
    pose_results = []
    
    for frame_idx in range(num_frames):
        if frame_idx in cached_poses:
            frame_poses = []
            for pose_dict in cached_poses[frame_idx]:
                keypoints = pose_dict['keypoints']
                
                # Extract only the requested number of keypoints
                # COCO-WholeBody has 133 keypoints, COCO has 17
                if len(keypoints) > num_keypoints:
                    keypoints = keypoints[:num_keypoints]
                
                frame_poses.append(keypoints)
            pose_results.append(frame_poses)
        else:
            # No poses for this frame
            pose_results.append([])
    
    return pose_results


def dist_ske(ske1, ske2):
    """Calculate distance between two skeletons for tracking."""
    dist = np.linalg.norm(ske1[:, :2] - ske2[:, :2], axis=1) * 2
    diff = np.abs(ske1[:, 2] - ske2[:, 2])
    return np.sum(np.maximum(dist, diff))


def pose_tracking(pose_results, max_tracks=2, thre=30):
    """
    Track poses across frames using Hungarian algorithm.
    
    Args:
        pose_results: List of lists, where each inner list contains keypoint arrays
        max_tracks: Maximum number of tracks to keep
        thre: Threshold for track proposal (frames since last seen)
        
    Returns:
        tuple: (keypoints, keypoint_scores) arrays of shape (max_tracks, num_frames, num_joints, 2/3)
    """
    tracks, num_tracks = [], 0
    num_joints = None
    
    for idx, poses in enumerate(pose_results):
        if len(poses) == 0:
            continue
        if num_joints is None:
            num_joints = poses[0].shape[0]
        track_proposals = [t for t in tracks if t['data'][-1][0] > idx - thre]
        n, m = len(track_proposals), len(poses)
        scores = np.zeros((n, m))

        for i in range(n):
            for j in range(m):
                scores[i][j] = dist_ske(track_proposals[i]['data'][-1][1], poses[j])

        row, col = linear_sum_assignment(scores)
        for r, c in zip(row, col):
            track_proposals[r]['data'].append((idx, poses[c]))
        if m > n:
            for j in range(m):
                if j not in col:
                    num_tracks += 1
                    new_track = dict(data=[])
                    new_track['track_id'] = num_tracks
                    new_track['data'] = [(idx, poses[j])]
                    tracks.append(new_track)
                    
    if num_joints is None:
        return None, None
        
    tracks.sort(key=lambda x: -len(x['data']))
    result = np.zeros((max_tracks, len(pose_results), num_joints, 3), dtype=np.float16)
    
    for i, track in enumerate(tracks[:max_tracks]):
        for item in track['data']:
            idx, pose = item
            result[i, idx] = pose
            
    return result[..., :2], result[..., 2]


def draw_keypoints_simple(frame: np.ndarray, keypoints: np.ndarray, 
                           conf_thresh: float = 0.3, 
                           color: tuple = (0, 255, 0),
                           radius: int = 3):
    """
    Draw keypoints on a frame with simple circles.
    
    Args:
        frame: BGR image to draw on (modified in place)
        keypoints: Array of shape (num_keypoints, 3) with (x, y, score)
        conf_thresh: Minimum confidence to draw keypoint
        color: BGR color tuple
        radius: Circle radius
    """
    for kpt in keypoints:
        x, y, score = kpt[0], kpt[1], kpt[2]
        if score > conf_thresh:
            cv2.circle(frame, (int(x), int(y)), radius, color, -1, lineType=cv2.LINE_AA)


# COCO skeleton connections for visualization
COCO_SKELETON = [
    (0, 1), (0, 2), (1, 3), (2, 4),  # Head
    (5, 6), (5, 7), (7, 9), (6, 8), (8, 10),  # Arms
    (5, 11), (6, 12), (11, 12),  # Torso
    (11, 13), (13, 15), (12, 14), (14, 16)  # Legs
]


def draw_skeleton_simple(frame: np.ndarray, keypoints: np.ndarray,
                          conf_thresh: float = 0.3,
                          kpt_color: tuple = (0, 255, 0),
                          link_color: tuple = (255, 128, 0),
                          radius: int = 3,
                          thickness: int = 2):
    """
    Draw skeleton with keypoints and connections on a frame.
    
    Args:
        frame: BGR image to draw on (modified in place)
        keypoints: Array of shape (num_keypoints, 3) with (x, y, score)
        conf_thresh: Minimum confidence to draw
        kpt_color: BGR color for keypoints
        link_color: BGR color for skeleton links
        radius: Keypoint circle radius
        thickness: Line thickness for skeleton
    """
    # Draw skeleton links
    for start_idx, end_idx in COCO_SKELETON:
        if start_idx < len(keypoints) and end_idx < len(keypoints):
            start_kpt = keypoints[start_idx]
            end_kpt = keypoints[end_idx]
            
            if start_kpt[2] > conf_thresh and end_kpt[2] > conf_thresh:
                start_pt = (int(start_kpt[0]), int(start_kpt[1]))
                end_pt = (int(end_kpt[0]), int(end_kpt[1]))
                cv2.line(frame, start_pt, end_pt, link_color, thickness, lineType=cv2.LINE_AA)
    
    # Draw keypoints on top
    draw_keypoints_simple(frame, keypoints, conf_thresh, kpt_color, radius)


def main():
    args = parse_args()

    # Resolve video path and output filename
    video_path = None
    out_filename = None
    video_meta = None
    
    if args.row_idx is not None:
        # Load video metadata and look up by row index
        print(f'[DEBUG] Loading video metadata from: {args.video_meta}')
        try:
            meta_lookup = load_video_metadata(args.video_meta)
        except FileNotFoundError:
            print(f"ERROR: Video metadata file not found: {args.video_meta}")
            return
        except Exception as e:
            print(f"ERROR: Failed to load video metadata: {e}")
            return
        
        video_meta = get_video_info_from_row(args.row_idx, meta_lookup)
        if video_meta is None:
            print(f"ERROR: Row index {args.row_idx} not found in video metadata")
            print(f"Valid row indices: 1 to {max(meta_lookup.keys())}")
            return
        
        video_path = video_meta.get('original_path')
        if not video_path or not Path(video_path).exists():
            print(f"ERROR: Video file not found: {video_path}")
            return
        
        print(f'[DEBUG] Row {args.row_idx}: {video_meta.get("FileName", "unknown")}')
        print(f'[DEBUG] Video path: {video_path}')
        
        # Auto-generate output filename
        if args.out_filename:
            out_filename = args.out_filename
        else:
            video_basename = Path(video_path).stem
            output_dir = Path(args.output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)
            out_filename = str(output_dir / f"row{args.row_idx}_{video_basename}_action.mp4")
        
    else:
        # Use explicit video path
        video_path = args.video
        if not Path(video_path).exists():
            print(f"ERROR: Video file not found: {video_path}")
            return
        
        if args.out_filename:
            out_filename = args.out_filename
        else:
            # Default output name based on input
            video_basename = Path(video_path).stem
            out_filename = f"{video_basename}_action.mp4"
    
    print(f'[DEBUG] Output will be saved to: {out_filename}')

    # Determine pose cache path
    if args.pose_cache:
        pose_cache_path = Path(args.pose_cache)
    else:
        pose_cache_path = get_sam3_pose_cache_path(video_path, args)
    
    print(f'[DEBUG] Looking for pose cache at: {pose_cache_path}')
    
    # Load cached poses
    try:
        cached_poses = load_pose_cache(pose_cache_path)
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        print(f"Please run batch_sam_pose.py first to generate pose cache, or specify --pose-cache")
        return
    except RuntimeError as e:
        print(f"ERROR: {e}")
        return

    print('[DEBUG] Starting frame extraction...')
    frame_paths, original_frames = frame_extraction(video_path, args.short_side)
    num_frame = len(frame_paths)
    h, w, _ = original_frames[0].shape
    print(f'[DEBUG] Extracted {num_frame} frames')

    print('[DEBUG] Loading action recognition config...')
    config = mmcv.Config.fromfile(args.config)
    config.data.test.pipeline = [x for x in config.data.test.pipeline if x['type'] != 'DecompressPose']
    
    # Are we using GCN for Inference?
    GCN_flag = 'GCN' in config.model.type
    print(f'[DEBUG] GCN_flag is set to {GCN_flag}')
    GCN_nperson = None
    if GCN_flag:
        format_op = [op for op in config.data.test.pipeline if op['type'] == 'FormatGCNInput'][0]
        # We will set the default value of GCN_nperson to 2, which is
        # the default arg of FormatGCNInput
        GCN_nperson = format_op.get('num_person', 2)

    print('[DEBUG] Initializing action recognition model...')
    model = init_recognizer(config, args.checkpoint, args.device)
    print('[DEBUG] Action recognition model loaded')

    # Load label_map
    label_map = [x.strip() for x in open(args.label_map).readlines()]

    # Convert cached poses to expected format
    print('[DEBUG] Converting cached poses to tracking format...')
    pose_results = convert_cached_poses_to_format(
        cached_poses, 
        num_frame, 
        num_keypoints=args.num_keypoints
    )
    
    # Log statistics
    frames_with_poses = sum(1 for p in pose_results if len(p) > 0)
    print(f'[DEBUG] Frames with poses: {frames_with_poses}/{num_frame}')
    
    torch.cuda.empty_cache()

    fake_anno = dict(
        frame_dir='',
        label=-1,
        img_shape=(h, w),
        original_shape=(h, w),
        start_index=0,
        modality='Pose',
        total_frames=num_frame)

    if GCN_flag:
        # We will keep at most `GCN_nperson` persons per frame.
        tracking_inputs = pose_results  # Already in correct format
        keypoint, keypoint_score = pose_tracking(tracking_inputs, max_tracks=GCN_nperson)
        fake_anno['keypoint'] = keypoint
        fake_anno['keypoint_score'] = keypoint_score
    else:
        num_person = max([len(x) for x in pose_results]) if pose_results else 0
        # Current PoseC3D models are trained on COCO-keypoints (17 keypoints)
        num_keypoint = args.num_keypoints
        keypoint = np.zeros((num_person, num_frame, num_keypoint, 2),
                            dtype=np.float16)
        keypoint_score = np.zeros((num_person, num_frame, num_keypoint),
                                  dtype=np.float16)
        for i, poses in enumerate(pose_results):
            for j, pose in enumerate(poses):
                keypoint[j, i] = pose[:, :2]
                keypoint_score[j, i] = pose[:, 2]
        fake_anno['keypoint'] = keypoint
        fake_anno['keypoint_score'] = keypoint_score

    if fake_anno['keypoint'] is None:
        action_label = ''
        print('[WARNING] No keypoints detected, cannot perform action recognition')
    else:
        print('[DEBUG] Running action recognition inference...')
        results = inference_recognizer(model, fake_anno)
        action_label = label_map[results[0][0]]
        print(f'[DEBUG] Predicted action: {action_label}')

    # Visualization
    print('[DEBUG] Generating visualization...')
    vis_frames = []
    
    for i, frame in enumerate(original_frames):
        vis_frame = frame.copy()
        
        # Draw poses for this frame
        if i < len(pose_results) and len(pose_results[i]) > 0:
            for pose in pose_results[i]:
                draw_skeleton_simple(
                    vis_frame, 
                    pose, 
                    conf_thresh=args.pose_conf_thresh,
                    kpt_color=(0, 255, 0),
                    link_color=(255, 128, 0)
                )
        
        # Add action label
        cv2.putText(vis_frame, action_label, (10, 30), FONTFACE, FONTSCALE,
                    FONTCOLOR, THICKNESS, LINETYPE)
        
        vis_frames.append(vis_frame)

    # Write output video using ffmpeg
    temp_dir = './tmp/output_frames'
    os.makedirs(temp_dir, exist_ok=True)

    # Save frames as temporary images
    for i, frame in enumerate(vis_frames):
        frame_path = osp.join(temp_dir, f'frame_{i:06d}.jpg')
        cv2.imwrite(frame_path, frame)

    # Use ffmpeg to create video from frames
    print('[DEBUG] Writing output video with ffmpeg...')
    
    # Ensure output directory exists
    out_dir = osp.dirname(out_filename)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    
    ffmpeg_cmd = [
        'ffmpeg', '-y',
        '-framerate', '24',
        '-i', osp.join(temp_dir, 'frame_%06d.jpg'),
        '-vf', 'pad=ceil(iw/2)*2:ceil(ih/2)*2',  # Ensure even dimensions for libx264
        '-c:v', 'libx264',
        '-pix_fmt', 'yuv420p',
        out_filename
    ]
    subprocess.run(ffmpeg_cmd, check=True)

    # Clean up temporary frames
    shutil.rmtree(temp_dir)

    tmp_frame_dir = osp.dirname(frame_paths[0])
    shutil.rmtree(tmp_frame_dir)

    print(f'[DEBUG] Output saved to: {out_filename}')
    print('[DEBUG] Done!')


if __name__ == '__main__':
    main()

